insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'SMART SENSE', 1, '2017-11-20');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Clorpres', 1, '2018-01-28');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Consultation', 'fluoxetine hydrochloride', 1, '2017-12-27');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'ULORIC', 1, '2017-07-13');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Consultation', 'Bacitracin', 1, '2018-04-14');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'Childrens Plus Cough and Runny Nose', 1, '2018-03-16');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Consultation', 'Leader Childrens Pain and Fever', 1, '2017-10-19');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'Kalium aceticum comp. 6', 1, '2018-02-13');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'Magnesium Sulfate', 1, '2018-04-21');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'Oxygen', 1, '2018-02-22');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Guaifenesin Phenylephrine Dextromethorphan', 1, '2018-01-26');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'ACREMONIUM STRICTUM', 1, '2017-09-21');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Standardized Mite D. farinae', 1, '2017-12-01');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Carboplatin', 1, '2017-10-01');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'Tramadol Hydrochloride', 1, '2017-08-24');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Promethazine Hydrochloride', 1, '2017-06-21');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Capecitabine', 1, '2017-10-01');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'Desonide', 1, '2017-06-03');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'Neomycin and Polymyxin B Sulfates and Bacitracin Zinc', 1, '2017-10-03');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'Lysol', 1, '2018-02-24');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'POLYETHYLENE GLYCOL 3350 AND ELECTROLYTES', 1, '2018-04-08');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Consultation', 'Isosorbide mononitrate', 1, '2017-06-17');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Depo-Medrol', 1, '2017-12-20');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'Doxepin Hydrochloride', 1, '2018-01-11');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'Terazosin Hydrochloride Anhydrous', 1, '2018-01-27');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Drugs Payment', 'Edluar', 1, '2018-03-02');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'ck one waterfresh face makeup spf 15', 1, '2018-02-18');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'formu care ibuprofen', 1, '2017-11-16');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Blood Test', 'ROPINIROLE HYDROCHLORIDE', 1, '2017-10-21');
insert into TransactionType (TransactionTypeName, Description, CreatedByID, CreatedDate) values ('Vital Sign Status', 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', 1, '2017-12-22');
